import { Download, ExternalLink, FileText, LoaderCircle, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import PageHeader from "../../common/components/dashboard/PageHeader";
import AlertMessage from "../../common/components/AlertMessage";
import { getMyStudents } from "../../services/mentorService";
import { createTask, deleteTask, downloadSubmissionFile, getStaffTasks, getTaskSubmissions, reviewTaskSubmission } from "../../services/taskService";
import { getApiErrorMessage } from "../../utils/apiError";

export default function TaskManagement() {
  const [tasks,setTasks]=useState([]), [students,setStudents]=useState([]), [error,setError]=useState(""), [success,setSuccess]=useState("");
  const [attachment,setAttachment]=useState(null), [selectedTask,setSelectedTask]=useState(null), [submissions,setSubmissions]=useState([]), [isSaving,setIsSaving]=useState(false);
  const [form,setForm]=useState({branchId:"",title:"",description:"",dueAt:"",studentIds:[],allowFileSubmission:true,allowGithubSubmission:true});
  const load=async()=>{try{const[a,b]=await Promise.all([getStaffTasks(),getMyStudents()]);setTasks(a);setStudents(Array.isArray(b)?b:(b.students||b.mentees||[]));}catch(e){setError(getApiErrorMessage(e))}};
  useEffect(()=>{load()},[]);
  const submit=async(e)=>{e.preventDefault();setIsSaving(true);setError("");try{await createTask({taskData:{...form,branchId:Number(form.branchId),studentIds:form.studentIds.map(Number),dueAt:form.dueAt},attachment});setForm({branchId:"",title:"",description:"",dueAt:"",studentIds:[],allowFileSubmission:true,allowGithubSubmission:true});setAttachment(null);setSuccess("Task created successfully.");load();}catch(e){setError(getApiErrorMessage(e))}finally{setIsSaving(false)}};
  const openSubmissions=async(task)=>{try{setSelectedTask(task);setSubmissions(await getTaskSubmissions(task.id));}catch(e){setError(getApiErrorMessage(e))}};
  const review=async(submission,status)=>{const feedback=status==="CHANGES_REQUIRED"?window.prompt("Enter feedback explaining required changes:"):window.prompt("Optional feedback:","Correct submission. Task approved.");if(status==="CHANGES_REQUIRED"&&!feedback?.trim())return;try{const updated=await reviewTaskSubmission({submissionId:submission.id,status,feedback});setSubmissions((current)=>current.map((x)=>x.id===updated.id?updated:x));setSuccess(`Submission ${status.toLowerCase().replaceAll("_"," ")}.`);}catch(e){setError(getApiErrorMessage(e))}};
  return <div><PageHeader eyebrow="Staff" title="Task management" description="Attach assignment files, assign tasks, and validate student submissions."/><div className="space-y-3"><AlertMessage type="success" message={success} onClose={()=>setSuccess("")}/><AlertMessage type="error" message={error} onClose={()=>setError("")}/></div>
    <form onSubmit={submit} className="mt-6 grid gap-4 rounded-2xl border bg-white p-6 shadow-sm">
      <input required type="number" min="1" placeholder="Branch ID" value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})} className="rounded-xl border p-3"/>
      <input required placeholder="Task title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="rounded-xl border p-3"/>
      <textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="rounded-xl border p-3"/>
      <input required type="datetime-local" value={form.dueAt} onChange={e=>setForm({...form,dueAt:e.target.value})} className="rounded-xl border p-3"/>
      <label className="rounded-xl border-2 border-dashed p-5 text-center"><FileText className="mx-auto"/><span className="mt-2 block font-semibold">Attach assignment PDF, document, ZIP or image</span><input type="file" accept=".pdf,.doc,.docx,.txt,.zip,.png,.jpg,.jpeg" className="mt-3" onChange={e=>setAttachment(e.target.files?.[0]||null)}/></label>
      <div className="flex flex-wrap gap-5"><label><input type="checkbox" checked={form.allowFileSubmission} onChange={e=>setForm({...form,allowFileSubmission:e.target.checked})}/> Allow file submission</label><label><input type="checkbox" checked={form.allowGithubSubmission} onChange={e=>setForm({...form,allowGithubSubmission:e.target.checked})}/> Allow GitHub submission</label></div>
      <div className="grid gap-2 sm:grid-cols-2">{students.map(s=><label key={s.id} className="rounded-xl border p-3"><input type="checkbox" checked={form.studentIds.includes(s.id)} onChange={()=>setForm({...form,studentIds:form.studentIds.includes(s.id)?form.studentIds.filter(x=>x!==s.id):[...form.studentIds,s.id]})}/> {s.fullName} ({s.cdacId})</label>)}</div>
      <button disabled={isSaving||form.studentIds.length===0} className="rounded-xl bg-indigo-600 p-3 font-semibold text-white disabled:bg-slate-300">{isSaving?<span className="inline-flex gap-2"><LoaderCircle className="animate-spin"/>Creating...</span>:"Create task"}</button>
    </form>
    <div className="mt-6 space-y-4">{tasks.map(t=><article key={t.id} className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="text-lg font-bold">{t.title}</h3><p className="mt-2 text-slate-600">{t.description}</p><p className="mt-2 text-sm text-slate-500">Due: {new Date(t.dueAt).toLocaleString("en-IN")}</p><div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>openSubmissions(t)} className="rounded-xl bg-indigo-600 px-4 py-2.5 font-semibold text-white">View submissions</button><button onClick={async()=>{if(confirm("Delete this task and all submissions?")){await deleteTask(t.id);load()}}} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-4 py-2.5 font-semibold text-red-600"><Trash2 size={17}/>Delete</button></div></article>)}</div>
    {selectedTask&&<div className="fixed inset-0 z-[80] flex items-center justify-center p-4"><button className="absolute inset-0 bg-slate-950/60" onClick={()=>setSelectedTask(null)}/><div className="relative z-10 max-h-[90vh] w-full max-w-5xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-sm font-semibold text-indigo-600">SUBMISSIONS</p><h2 className="text-2xl font-bold">{selectedTask.title}</h2></div><button onClick={()=>setSelectedTask(null)}>✕</button></div>{submissions.length===0?<p className="mt-8 rounded-xl bg-slate-50 p-8 text-center">No submissions yet.</p>:<div className="mt-6 overflow-x-auto"><table className="min-w-full"><thead><tr className="bg-slate-50 text-left"><th className="p-3">Student</th><th className="p-3">Attempt</th><th className="p-3">Submission</th><th className="p-3">Status</th><th className="p-3">Review</th></tr></thead><tbody>{submissions.map(s=><tr key={s.id} className="border-t"><td className="p-3"><b>{s.studentName}</b><br/><span className="text-sm text-slate-500">{s.studentCdacId}</span></td><td className="p-3">{s.attemptNumber}<br/><span className={s.lateSubmission?"text-red-600":"text-emerald-600"}>{s.lateSubmission?"Late":"On time"}</span></td><td className="p-3"><div className="flex flex-col gap-2">{s.hasFile&&<button onClick={()=>downloadSubmissionFile(s.id)} className="inline-flex items-center gap-2 text-indigo-600"><Download size={16}/>Download file</button>}{s.githubUrl&&<a href={s.githubUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-indigo-600"><ExternalLink size={16}/>GitHub</a>}</div></td><td className="p-3 font-semibold">{s.status}</td><td className="p-3"><div className="flex gap-2"><button disabled={s.status==="APPROVED"} onClick={()=>review(s,"APPROVED")} className="rounded-lg bg-emerald-600 px-3 py-2 text-white disabled:opacity-40">Approve</button><button disabled={s.status==="APPROVED"} onClick={()=>review(s,"CHANGES_REQUIRED")} className="rounded-lg bg-amber-500 px-3 py-2 text-white disabled:opacity-40">Request changes</button></div></td></tr>)}</tbody></table></div>}</div></div>}
  </div>;
}
